export interface GlossaryTerm {
  term: string;
  def: string;
  category: "Cards & rarity" | "Products" | "Condition & grading" | "Market & collecting" | "Slang";
}

export const GLOSSARY: GlossaryTerm[] = [
  // --- Cards & rarity ---
  { term: "Common / Uncommon / Rare", def: "The base rarity ladder printed on every card (circle, diamond, and star symbol respectively, bottom of the card). Most monetary value lives above plain 'Rare'.", category: "Cards & rarity" },
  { term: "Holo (Holofoil)", def: "A card whose artwork box has a foil (shiny) treatment. 'Holo rare' is the classic premium card of older eras.", category: "Cards & rarity" },
  { term: "Reverse Holo", def: "A card where everything except the artwork is foiled. Nearly every modern pack contains one; reverse holos of key cards can carry premiums.", category: "Cards & rarity" },
  { term: "Full Art", def: "A card whose artwork covers the entire card face, usually with textured foil. Common for Supporters and Pokémon ex/V.", category: "Cards & rarity" },
  { term: "Alt Art / Alternate Art", def: "A special version of a card with completely different, often scenic artwork. Alt arts (especially from Sword & Shield) are some of the most chased modern cards.", category: "Cards & rarity" },
  { term: "Illustration Rare (IR)", def: "Scarlet & Violet-era rarity for artwork-focused cards of regular Pokémon; marked with one gold star. Spiritual successor to alt arts.", category: "Cards & rarity" },
  { term: "Special Illustration Rare (SIR)", def: "Scarlet & Violet-era rarity for artwork-focused versions of ex Pokémon and Supporters; marked with two gold stars. Usually a set's top chase cards.", category: "Cards & rarity" },
  { term: "Hyper Rare / Gold Card", def: "Gold-bordered, gold-foil cards, typically the last cards in a set's secret-rare numbering.", category: "Cards & rarity" },
  { term: "Secret Rare", def: "Any card whose collector number exceeds the set's printed total (e.g. 200/191). Includes golds, rainbows, and some SIRs.", category: "Cards & rarity" },
  { term: "Rainbow Rare", def: "Sun & Moon / Sword & Shield-era secret rares with a rainbow foil finish over the whole card.", category: "Cards & rarity" },
  { term: "ex / EX / GX / V / VMAX / VSTAR", def: "Mechanics printed on powerful Pokémon across different eras (lowercase 'ex' = EX era and again in Scarlet & Violet; 'EX' = XY era; GX = Sun & Moon; V family = Sword & Shield). Their rare versions anchor most sets' value.", category: "Cards & rarity" },
  { term: "Trainer Gallery / Character Rare", def: "Subsets showing a Pokémon together with its trainer (e.g. TG numbering in late Sword & Shield sets). Popular with collectors.", category: "Cards & rarity" },
  { term: "Promo Card", def: "A card issued outside booster packs — in blisters, boxes, events, or magazines. Marked with a black star promo number.", category: "Cards & rarity" },
  { term: "First Edition (1st Ed.)", def: "Wizards-era (1999–2003) cards with a '1st Edition' stamp from the first print run. Dramatically more valuable than unlimited prints.", category: "Cards & rarity" },
  { term: "Shadowless", def: "Early Base Set print run lacking the drop shadow beside the artwork box. Sits between 1st Edition and Unlimited in scarcity and price.", category: "Cards & rarity" },
  { term: "Unlimited", def: "The standard (non-1st-Edition) print run of a Wizards-era set.", category: "Cards & rarity" },
  { term: "Error / Misprint", def: "A card with a printing mistake (miscut, ink error, wrong stamp). Some errors are famous and collectible; most add little value.", category: "Cards & rarity" },
  { term: "Regulation Mark", def: "The letter (D, E, F, G, H…) on modern cards that determines tournament legality. Irrelevant to most collectors, important to players.", category: "Cards & rarity" },
  { term: "Collector Number", def: "The 'X/Y' number at the bottom of a card (e.g. 199/165). Numbers above the set total are secret rares.", category: "Cards & rarity" },
  { term: "Poké Ball / Master Ball Foil", def: "Special pattern foils (introduced in Japanese sets, then in sets like Prismatic Evolutions) where the holo pattern is made of tiny Poké Balls or Master Balls.", category: "Cards & rarity" },

  // --- Products ---
  { term: "Booster Pack", def: "The basic sealed unit — 10–11 cards in modern sets. 'Loose packs' are sold individually outside a box.", category: "Products" },
  { term: "Booster Box", def: "A factory-sealed box of 36 booster packs (modern English standard). The benchmark for sealed collecting and $/pack math.", category: "Products" },
  { term: "Elite Trainer Box (ETB)", def: "A branded box with 8–9 packs, 65 sleeves, energies, dice, and accessories. Pokémon Center versions add an extra promo and usually sell at a premium.", category: "Products" },
  { term: "Booster Bundle", def: "A slim box of 6 packs with no accessories — often the cheapest way to buy packs at retail.", category: "Products" },
  { term: "Sleeved Booster", def: "A single pack hung in cardboard/plastic for retail pegs. Identical odds to any other pack of the set.", category: "Products" },
  { term: "Blister", def: "Retail packaging combining packs with a promo card and/or coin — 'single pack blister' (1 pack) or '3-pack blister' (3 packs + promo).", category: "Products" },
  { term: "Ultra-Premium Collection (UPC)", def: "Top-shelf boxed product (usually 10–16 packs) with metal promo cards and premium accessories, e.g. the Charizard UPC.", category: "Products" },
  { term: "Collection Box", def: "Catch-all for promo-led boxed products: an exclusive promo (often an ex/V) plus a handful of packs.", category: "Products" },
  { term: "Tin", def: "A metal tin with 4–5 packs and a promo. Mini tins hold 2 packs and an art card.", category: "Products" },
  { term: "Build & Battle Box", def: "Prerelease product: 4 packs plus a 40-card kit with exclusive stamped promos, sold around a set's launch.", category: "Products" },
  { term: "Theme Deck / League Battle Deck", def: "Ready-to-play preconstructed decks. Vintage theme decks are collectible sealed items in their own right.", category: "Products" },
  { term: "Case", def: "A sealed carton of multiple boxes as shipped to stores (e.g. 6 booster boxes). Traded by serious sealed investors.", category: "Products" },
  { term: "Booster Box Case Fresh", def: "Packs or boxes taken directly from a sealed case — shorthand for 'guaranteed untampered'.", category: "Products" },
  { term: "Code Card", def: "The card in each pack redeemable in Pokémon TCG Live. Bulk code cards sell for a few cents each.", category: "Products" },

  // --- Condition & grading ---
  { term: "Raw", def: "An ungraded card, as pulled or bought. Priced by condition tier (NM, LP, …).", category: "Condition & grading" },
  { term: "NM / LP / MP / HP / DMG", def: "Condition ladder: Near Mint, Lightly Played, Moderately Played, Heavily Played, Damaged. Most market prices you see quoted are NM.", category: "Condition & grading" },
  { term: "Slab", def: "A card graded and sealed in a tamper-evident case by a grading company.", category: "Condition & grading" },
  { term: "PSA / BGS / CGC", def: "The three major grading companies. PSA dominates Pokémon resale value; BGS 'black label' 10s and CGC 'pristine' 10s have their own followings.", category: "Condition & grading" },
  { term: "PSA 10 (Gem Mint)", def: "The benchmark top grade. The price gap between a PSA 10 and a PSA 9 of the same card is often enormous.", category: "Condition & grading" },
  { term: "Grading Scale", def: "1–10 scale used by graders, judging centering, corners, edges, and surface.", category: "Condition & grading" },
  { term: "Centering", def: "How evenly the artwork is positioned between borders (e.g. 55/45). The most common reason a clean card misses a 10.", category: "Condition & grading" },
  { term: "Whitening", def: "White wear on a card's edges or back corners — a major grade killer, visible under light.", category: "Condition & grading" },
  { term: "Pop Report (Population)", def: "A grading company's public count of how many copies of a card exist at each grade — low pop = scarce in top grade.", category: "Condition & grading" },
  { term: "Penny Sleeve + Toploader", def: "The standard cheap protection combo: a soft sleeve inside a rigid plastic holder. How raw cards should be shipped and stored.", category: "Condition & grading" },

  // --- Market & collecting ---
  { term: "Chase Card", def: "The card(s) collectors most want from a set — usually its most valuable SIRs, alt arts, or iconic Pokémon. PokéChase auto-ranks these per set.", category: "Market & collecting" },
  { term: "Grail", def: "A collector's ultimate target card — high value, high emotional weight. On this site: a set's top-3 cards at $100+.", category: "Market & collecting" },
  { term: "Hit", def: "Any meaningfully valuable pull from a pack — 'the box had three hits'.", category: "Market & collecting" },
  { term: "Pull / Pull Rates", def: "What you open from packs; pull rates are the estimated odds of each rarity appearing (published unofficially by pack-opening data sites).", category: "Market & collecting" },
  { term: "Market Price", def: "TCGplayer's algorithmic estimate of a card's going rate based on actual sales — the number PokéChase tracks daily.", category: "Market & collecting" },
  { term: "Spread (Low/Mid/High)", def: "The range of current listings. A wide gap between low and market often signals thin supply or condition variance.", category: "Market & collecting" },
  { term: "Comps", def: "Recently sold listings ('comparables') used to judge what a card is really worth — check eBay sold filters, not asking prices.", category: "Market & collecting" },
  { term: "EV (Expected Value)", def: "The average value of the cards inside a sealed product, computed from pull rates × card prices. If a box's EV is far below its cost, buy singles instead.", category: "Market & collecting" },
  { term: "Singles", def: "Individual cards bought outright — almost always the cheapest way to get a specific card versus opening packs.", category: "Market & collecting" },
  { term: "Sealed Collecting / Investing", def: "Holding unopened product long-term on the theory that supply only shrinks. Slow, storage-hungry, and not guaranteed — treat as collecting first.", category: "Market & collecting" },
  { term: "Master Set", def: "Collecting every card in a set including all secret rares and (for completionists) reverse holos. A 'set completion' goal is the base set only.", category: "Market & collecting" },
  { term: "Playset", def: "Four copies of a card — the maximum allowed in a tournament deck. A player's buying unit, not a collector's.", category: "Market & collecting" },
  { term: "Binder Collection", def: "Collecting into binder pages by set or theme rather than for resale. Use side-loading pages for anything valuable.", category: "Market & collecting" },
  { term: "Vintage vs Modern", def: "Community shorthand: 'vintage' ≈ Wizards era (1999–2003), 'classic' ≈ EX–HGSS, 'modern' ≈ XY onward. Vintage carries scarcity value; modern is print-run heavy.", category: "Market & collecting" },
  { term: "Print Run / Reprint", def: "How much of a set was manufactured. The Pokémon Company reprints popular modern sets aggressively, which caps sealed appreciation short-term.", category: "Market & collecting" },
  { term: "Spot Price", def: "A card's current market value right now — as opposed to what it sold for last month. Prices move; check the chart.", category: "Market & collecting" },
  { term: "Buylist", def: "The price a store will pay you for a card (typically 50–70% of market in credit, less in cash).", category: "Market & collecting" },
  { term: "Arbitrage / Flipping", def: "Buying underpriced cards or sealed product to resell. Fees (~13–15% on major platforms) plus shipping eat most casual margins.", category: "Market & collecting" },
  { term: "FOMO Tax", def: "Slang for the price premium on a set in the hype window right after release. Prices for most modern chase cards drift down for 2–3 months after launch as supply floods in.", category: "Market & collecting" },

  // --- Slang ---
  { term: "God Pack", def: "An ultra-rare pack in which every slot is a hit (a Japanese-set phenomenon, e.g. VSTAR Universe). English sets don't have true god packs.", category: "Slang" },
  { term: "Mapping", def: "Using pack-search techniques or box patterns to find hit packs. Considered cheating; buy from sealed boxes or reputable sellers to avoid mapped packs.", category: "Slang" },
  { term: "Weighed Packs", def: "Loose packs weighed to remove the ones containing holo hits (a vintage-era scam). Another reason loose vintage packs are risky buys.", category: "Slang" },
  { term: "Heavy / Light Pack", def: "The vocabulary of pack-weighing — 'heavy' packs likely contain an extra-thick holo card.", category: "Slang" },
  { term: "Resealed", def: "A pack or box opened, stripped of hits, and glued shut for resale. Buy sealed product only from trustworthy sources.", category: "Slang" },
  { term: "Pack Fresh", def: "A card straight from the pack, presumed mint. Not a guarantee — factory damage exists.", category: "Slang" },
  { term: "Bulk", def: "Low-value commons/uncommons/basic rares. Sold by the thousand-count box for pennies per card.", category: "Slang" },
  { term: "Zard", def: "Charizard. The single biggest price driver in the hobby — 'zard tax' explains why anything Charizard costs more.", category: "Slang" },
  { term: "Slab City", def: "A collection heavy on graded cards.", category: "Slang" },
  { term: "The Dip", def: "The post-release price decline of modern chase cards as supply is opened. Patient buyers 'buy the dip' 2–4 months after launch.", category: "Slang" },
  { term: "LGS", def: "Local Game Store — often price-competitive on singles and the best place to see product before buying.", category: "Slang" },
  { term: "MSRP", def: "Manufacturer's suggested retail price (e.g. $161.64 for a modern 36-pack booster box at $4.49/pack). Paying far above MSRP for in-print product is usually a mistake.", category: "Slang" },
  { term: "Chase the Bag", def: "Buying purely for profit rather than enjoyment. Historically the fastest way to overpay at hype peaks.", category: "Slang" },
  { term: "Rip", def: "To open packs ('rip a box'). 'Rip and ship' streams open product live and mail you the pulls.", category: "Slang" },
  { term: "Pull Tax", def: "The premium you pay opening packs for a specific card versus just buying the single.", category: "Slang" },
];
